spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql:inventory
    username: test
    password: test
    poolName: SpringBootHikariCP
    hikari:
      connectionTestQuery: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties.hibernate:
      cache:
        use_second_level_cache: false
        use_query_cache: false
  http.multipart:
    maxFileSize: 10MB
    maxRequestSize: 10MB

error.whitelabel.enabled: false

security:
  basic.enabled: false

logging:
  level:
    com.kinetic: INFO

    
server:
  contextPath: /inventory
    
---

spring:
  profiles: dev
  devtools.livereload.enabled: true
  jpa:
    show-sql: true

logging:
  level:
    com.kinetic: DEBUG
    com.zaxxer: DEBUG

error.whitelabel.enabled: true
